meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: consul_docker_z1
    templates:
      # run docker daemon
      - {name: docker, release: docker}
      # warm docker image cache from bosh package
      - {name: consul_docker_image, release: consul-docker}
      # run containers (see properties.containers)
      - {name: containers, release: docker}
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10

networks: (( merge ))

properties:
  containers:
    - name: consul
      image: "progrium/consul"
      command: "--server --bootstrap-expect=1"
      bind_ports:
        - "8300:8300"
        - "8500:8500"
        - "8600:8600"
      bind_volumes:
        - "/data"
      memory: "256m"
